insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (1, 'Puma Thunder Spectra', 42, 'Multicolor', 151.334, 12);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (2, 'Adidas x Raf Simons Replicant Ozweego', 41.5, 'Verdes y Grises', 115.823, 12);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (3, 'Nike Air Max 97 Silver Bullet', 40, 'Roja y Naranja', 248.892, 15);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (4, 'Reebok x Vetements Genetically Modified Pump', 44, 'Naranja y Azul', 128.265, 8);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (5, 'Air Jordan Black Cat', 39, 'Marrones y Verdes', 160.93, 18);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (6, 'Nike Cortez', 36.5, 'Naranja y Azul', 126.371, 21);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (7, 'Mizuno Wave Raider Phoenix', 39, 'Verdes y Grises', 147.21, 26);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (8, 'Nike Dunk Jedi', 44, 'Roja y Naranja', 172.117, 19);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (9, 'Saucony Kinvara', 39, 'Naranja y Azul', 114.347, 27);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (10, 'Nike Lebron 8 James Dean', 37, 'Roja y Naranja', 177.449, 6);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (11, 'Our Legacy Poseidon', 43, 'Roja y Naranja', 88.521, 8);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (12, 'Assassins', 36.5, 'Beijing', 195.013, 20);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (13, 'Converse All Star', 44.5, 'Verdes y Grises', 66.937, 30);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (14, 'New Balance 99X', 39.5, 'Beijing', 84.653, 18);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (15, 'Nike Cortez', 42, 'Marrones y Verdes', 127.015, 19);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (16, 'Vans Off The Wall', 35.5, 'Naranja y Azul', 64.496, 17);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (17, 'Adidas Gazelle', 41, 'Beijing', 136.916, 22);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (18, 'Reebok Classic', 39.5, 'Beijing', 79.572, 25);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (19, 'Ascics Tiger Corsair', 37, 'Roja y Naranja', 158.889, 12);
insert into mercaderia (idMercaderia, nombreMercaderia, tallaMercaderia, colorMercaderia, precioMercaderia, cantidadStock) values (20, 'Adidas Superstar', 36.5, 'Twins', 120.647, 17);
